### ISSUE TITLE
As a user office I should be able to preview the questionnaire template

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/issue-tracker#277] opened 2021-11-11 14:10 UTC
To increase the user experience ideally the user officer should be able to preview the new questionnaire template. This is important if they need to modify the existing questionnaire and be able to validate that what they want is what the submitter sees.

**Comment by simonfernandes** [comment] 2022-10-31 11:00
Is this a duplicate of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/132?

**Comment by simonfernandes** [comment] 2024-04-09 11:19
Notes from backlog pruning with George and Emma:

We can do this now

**Closed by simonfernandes** 2024-04-09 11:19 UTC
Labels: origin: project, type: feature, area: uop/stfc
