### ISSUE TITLE
LSF users will be able to see the PDFs of their legacy proposals

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/issue-tracker#124] opened 2021-05-19 09:42 UTC
Import of the old static generated PDF from the proposal database (`proposal_blob`).

Work involved in sharing the static generated PDF instead of the new system's dynamically generated one in the `user-office-factory`.

**Comment by TickleThePanda** [comment] 2021-09-06 14:00
I'm closing this as unresolved to better reflect what we need to do vs what we might do.

**Comment by TickleThePanda** [comment] 2021-09-06 14:08
Moved them to improvements instead.

**Comment by simonfernandes** [comment] 2024-04-09 10:42
Notes from backlog pruning with George and Emma:

Duplicate of https://github.com/UserOfficeProject/issue-tracker/issues/758

**Closed by simonfernandes** 2024-04-09 10:42 UTC
Labels: origin: project, size: 5, type: feature, status: blocked, area: uop/stfc
